# Generated by Django 5.2.10 on 2026-08-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcserver', '0002_add_celery_chain_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='source_states',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
    ]
